version: '3.8'

services:
  research-agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - LANGSMITH_OTEL_ENABLED=${LANGSMITH_OTEL_ENABLED}
    volumes:
      - .:/app
      - /app/__pycache__
    restart: unless-stopped
    
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=stock_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 